eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    enable-self-preservation: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
